name: 'WordPress Plugin Checks'
on: # rebuild any PRs and main branch changes
  push:
    branches:
    - main
    - develop
    - add/plugin-check # We'll want to remove this prior to the PR #271 being merged

  pull_request:
    branches:
      - main
      - develop
      - add/plugin-check # We'll want to remove this prior to the PR #271 being merged

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run plugin check
      uses: faisal-alvi/plugin-check-action@v1
      with:
        exclude-checks: |
          plugin_readme
          plugin_updater
          file_type
          trademarks
          direct_db_queries
          performant_wp_query_params
          enqueued_scripts_in_footer
          plugin_header_text_domain
        
        exclude-directories: |
          .github
          node_modules
          vendor
          tests
          bin
          build
          build
          assets

        exclude-files: |
          .eslintignore
          .eslintrc.js
          .gitignore
          .nvmrc
          .gitattributes
          .phpcs.xml.dist
          .wp-env.json
          .prettierrc.js
          .stylelintrc.json
